export enum WorkspaceType {
  PERSONAL = 'PERSONAL',
  TEAM = 'TEAM',
}

export enum WorkspaceRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
  VIEWER = 'VIEWER',
}

export enum FileStatus {
  PENDING_UPLOAD = 'PENDING_UPLOAD',
  ACTIVE = 'ACTIVE',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  DELETED = 'DELETED',
}

export enum AIStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum NotificationType {
  COMMENT = 'COMMENT',
  MENTION = 'MENTION',
  INVITATION = 'INVITATION',
  ROLE_CHANGED = 'ROLE_CHANGED',
  FILE_SHARED = 'FILE_SHARED',
  AI_PROCESSING_FAILED = 'AI_PROCESSING_FAILED',
}

export enum ActivityAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  WORKSPACE_CREATED = 'WORKSPACE_CREATED',
  WORKSPACE_MEMBER_ADDED = 'WORKSPACE_MEMBER_ADDED',
  WORKSPACE_MEMBER_REMOVED = 'WORKSPACE_MEMBER_REMOVED',
  WORKSPACE_ROLE_CHANGED = 'WORKSPACE_ROLE_CHANGED',
  FILE_UPLOADED = 'FILE_UPLOADED',
  FILE_DELETED = 'FILE_DELETED',
  FILE_DOWNLOADED = 'FILE_DOWNLOADED',
  COMMENT_CREATED = 'COMMENT_CREATED',
  COMMENT_DELETED = 'COMMENT_DELETED',
  MENTION_CREATED = 'MENTION_CREATED',
  AI_PROCESSING_COMPLETED = 'AI_PROCESSING_COMPLETED',
  AI_PROCESSING_FAILED = 'AI_PROCESSING_FAILED',
  AI_REPROCESS_REQUESTED = 'AI_REPROCESS_REQUESTED',
}
