export enum WorkspaceType {
  PERSONAL = 'PERSONAL',
  TEAM = 'TEAM',
}

export enum WorkspaceRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  EDITOR = 'EDITOR',
  VIEWER = 'VIEWER',
}

export enum FileStatus {
  PENDING_UPLOAD = 'PENDING_UPLOAD',
  ACTIVE = 'ACTIVE',
  UPLOAD_FAILED = 'UPLOAD_FAILED',
  DELETED = 'DELETED',
}

export enum AIStatus {
  NOT_STARTED = 'NOT_STARTED',
  PROCESSING = 'PROCESSING',
  READY = 'READY',
  FAILED = 'FAILED',
}

export enum NotificationType {
  COMMENT = 'COMMENT',
  MENTION = 'MENTION',
  INVITATION = 'INVITATION',
  ROLE_CHANGED = 'ROLE_CHANGED',
  FILE_SHARED = 'FILE_SHARED',
}

export enum ActivityAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  WORKSPACE_CREATE = 'WORKSPACE_CREATE',
  WORKSPACE_UPDATE = 'WORKSPACE_UPDATE',
  FILE_UPLOAD = 'FILE_UPLOAD',
  FILE_DOWNLOAD = 'FILE_DOWNLOAD',
  FILE_DELETE = 'FILE_DELETE',
  COMMENT_CREATE = 'COMMENT_CREATE',
  MEMBER_INVITE = 'MEMBER_INVITE',
  MEMBER_REMOVE = 'MEMBER_REMOVE',
  ROLE_CHANGE = 'ROLE_CHANGE',
}
